/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
